repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml

  # Ruff: Linter y Formatter (Configurado en tool.ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # Hooks Locales: Ejecutan las herramientas de tu grupo 'dev'
  - repo: local
    hooks:
      - id: dprint
        name: dprint (Formatter)
        entry: uv run dprint fmt
        language: system
        files: \.(md|toml)$

      - id: bandit
        name: Bandit (Security Audit)
        entry: uv run bandit
        args: ["-r", "src/", "-ll"]
        pass_filenames: false
        language: system
        types: [python]

      - id: vulture
        name: Vulture (Dead Code)
        entry: uv run vulture
        language: system
        types: [python]

      - id: deptry
        name: Deptry (Dependency Check)
        entry: uv run deptry .
        language: system
        always_run: true
        pass_filenames: false

      - id: pytest
        name: Pytest (Unit tests)
        entry: uv run pytest -m unit
        language: system
        pass_filenames: false
        always_run: true
