site_name: Benjamín Criado - Arquitectura & R&D
site_author: Benjamín Criado
site_description: Portfolio de Arquitectura y R&D
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bajmein
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benjamin-criado

nav:
  - Home: index.md
  - Vigilia: vigilia/index.md
  - Forge: forge/index.md
  - Laboratorio: laboratorio/index.md
  - CV: cv.md
